config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'home/index'
  get 'home/about'
  
  root 'home#index'

  post "/" => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    validates :ticker, presence: true
    validates :ticker, format: {without: /\s/}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api = StockQuote::Stock.new(api_key: 'pk_61becff1e4974bacba63b255c413dc6f')
    if params[:ticker] == ""
      @nothing = "Hey! You Forgot To Enter A Symbol"
    elsif params[:ticker]
      @stock = StockQuote::Stock.quote(params[:ticker])
    end
  end

  def about
  end
  
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg|%>
    <div class= 'alert alert-warning alert-dismissable' role= 'alert'>
        <button class='close' data-dismiss='alert'>
            <small><sup>x</sup></small>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'StockApp', root_path, class: 'navbar-brand' %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    

        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link'%>
            </li>
             <li class="nav-item">
                <%= link_to 'My Watchlist', stocks_path, class: 'nav-link'%>
            </li>
             <li class="nav-item">
                <%= link_to 'Add Stock', new_stock_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'%>
            </li>
        <% else%>
            <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
                <%= link_to 'Login', new_user_session_path, class: 'nav-link'%>
            </li>
        <% end %>
        
        
    
      </ul>
      <form class="justify-content-end">
        <input class="justify-content-end" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-secondary justify-content-end" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Me</h1>

<p> My name is Austin </p>

app/views/home/index.html.erb
<h1>StockApp</h1>

<%= form_tag root_path, :method => 'POST' do %>
    <%= text_field_tag 'ticker', nil, placeholder: 'Enter Ticker Symbol', size: 50 %>
    <%= submit_tag 'Lookup' %>
<% end %>


<% if @stock%>
    <%= @stock.company_name %> </br>
    $<%= @stock.latest_price %> </br>
<% elsif @nothing %>
    <%= @nothing %>
<% end %>


<% if @error %>
    <%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockapp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>

    <div class='container'>
    <%= render 'home/flash' %>
    </br>
      <%= yield %>
    </div>

  </body>
</html>

app/views/stocks/_add_stock.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class='table'>
    <tr>
      <td>
        <div class="field">
         <center> <%= form.text_field :ticker, placeholder: 'Ticker' %></center>
        </div>
      </td>
    </tr>

        <div class="field">
         <center> <%= form.number_field :user_id, value: current_user.id, type: 'hidden' %> </center>
          
        </div>
    <tr>
      <td>
        <div class="actions">
         <center> <%= form.submit 'Add Stock' %> </center>
        </div>
      </td>
    </tr>
  </table>
<% end %>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class='table'>
    <tr>
      <td>
        <div class="field">
          <%= form.label :ticker %>
          <%= form.text_field :ticker %>
        </div>
      </td>
    </tr>

        <div class="field">
          <%= form.number_field :user_id, value: current_user.id, type: 'hidden' %>
          
        </div>
    <tr>
      <td>
        <div class="actions">
          <%= form.submit %>
        </div>
      </td>
    </tr>
  </table>
<% end %>

app/views/stocks/_stats_table.html.erb
<% @api = StockQuote::Stock.new(api_key: 'pk_61becff1e4974bacba63b255c413dc6f') %>
            <% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
            <% @logo = StockQuote::Stock.logo(@stock.ticker)%>
            <% @company = StockQuote::Stock.company(@stock.ticker) %>
            <% @stats = StockQuote::Stock.stats(@stock.ticker) %>
            <% @chart = StockQuote::Stock.chart(@stock.ticker) %>

        <% @chart_hash_values = @chart.chart[0].values %>
        <% @high = @chart_hash_values[1]%>
        <% @low = @chart_hash_values[2]%>
        
            

<table class = 'table table-striped'>
    <thead>
        <th>Stats</th>
    </thead>

    <tbody>
        <tr>
            <td>Open: <%= number_with_precision(@ticker.open, :precision => 2, :delimiter => ',') %></td>
            <td>Volume: <%= number_with_precision(@ticker.volume, :precision => 2, :delimiter => ',') %></td>
        </tr>
        <tr>
            <td>High: <%= @high %></td>
            <td>Avg Vol: <%=number_with_precision(@ticker.avg_total_volume, :precision => 2, :delimiter => ',')  %></td>
        </tr>
         <tr>
            <td>Low: <%= @low %></td>
            <td>Mkt Cap: <%=number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',')  %></td>
        </tr>
         <tr>
            <td>52 Wk High: <%= @ticker.week52_high %></td>
            <td>P/E Ratio: <%= @ticker.pe_ratio %></td>
        </tr>
         <tr>
            <td>52 Wk Low: <%= @ticker.week52_low %></td>
            <td>Div/Yield: <%= number_with_precision(@stats.dividend_yield, :precision => 2, :delimiter => ',') %></td>
        </tr>
    
    
    </tbody>

<% @chart.inspect %>
    

app/views/stocks/_stock_form.html.erb
<% @api = StockQuote::Stock.new(api_key: 'pk_61becff1e4974bacba63b255c413dc6f') %>
            <% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
            <% @logo = StockQuote::Stock.logo(@stock.ticker)%>
            <% @company = StockQuote::Stock.company(@stock.ticker) %>
            
                <% if !@stock.ticker%>
                    The ticker: <%= @stock.ticker %></br> does not exist!
                <% else %>
                  <img src="<%= @logo.url %>"></br>
                  <strong><%= link_to @ticker.company_name %></strong></br></br>
                  Industry: <%= @company.industry %></br>
                  Current Price: $<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',')  %></br>
                  Previous Close: $<%= number_with_precision(@ticker.previous_close, :precision => 2, :delimiter => ',')%></br>
                  Percent Change: <%= @ticker.change_percent %>%  </br>
                  YTD Change: <%= number_with_precision(@ticker.ytd_change, :precision => 2, :delimiter => ',')%>% </br>
                  
                
                
              <% end %>
              
    </br>
    <%= link_to 'Remove', @stock, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Back', stocks_path %>


   

app/views/stocks/_watchlist_table.html.erb
<table class = 'table table-striped table-bordered table-hover'>
  <thead class = 'thead-dark'>
    <tr>
      <th>Company</th>
      <th>Ticker</th>
      <th>Current Price</th>
      <th>Market Cap</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <% if stock.user_id == current_user.id %>
         <% @api = StockQuote::Stock.new(api_key: 'pk_61becff1e4974bacba63b255c413dc6f') %>
         <% @ticker = StockQuote::Stock.quote(stock.ticker) %>
            <% if !stock.ticker%>
              <tr>
                <td><%= link_to 'Error', stock %></td>
                <td><%= stock.ticker %></td>
                <td>N/A</td>
                <td>N/A</td>
                <td><center><%= link_to 'Remove', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
              </tr>
            <% else %>
              <tr>
                <td><%= link_to @ticker.company_name, stock %></td>
                <td><%= @ticker.symbol %></td>
                <td>$<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',')  %></td>
                <td><%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',')%></td>
                <td><center><%= link_to 'Remove', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
              </tr>
          <% end %>
          
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path, class: 'btn btn-outline-secondary' %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<%= render 'watchlist_table' %>

app/views/stocks/new.html.erb
<div class = 'col-md-6 offset-md-3'>
  <div class = 'jumbotron jumbotron-secondary'>
   <center> <h1>New Stock</h1>
    <%= render 'add_stock', stock: @stock %>
    <%= link_to 'Back', stocks_path %></center>
  </div>
</div>

app/views/stocks/show.html.erb
<div class = 'col-md-6 offset-md-3'>
  <div class = 'jumbotron jumbotron-secondary'>
    <%= render 'stock_form' %>
    
  </div>
    <%= render 'stats_table' %>
</div>